dist: xenial

before_install:
  - sudo apt-get install -y hugo
addons:
  apt:
    update: true

script:
  - hugo version
  - bash ./deploy.sh

branches:
  only:
  - master

env:
  global:
  - ENCRYPTION_LABEL: "1d12f124072e"
  - COMMIT_AUTHOR_EMAIL: "wenzhixin2010@gmail.com"
