dist: xenial

before_install:
  - export VER="0.53"
  - wget https://github.com/gohugoio/hugo/releases/download/v${VER}/hugo_${VER}_Linux-64bit.deb
  - sudo dpkg -i hugo_${VER}_Linux-64bit.deb

script:
  - hugo version
  - bash ./deploy.sh

branches:
  only:
  - master

env:
  global:
  - ENCRYPTION_LABEL: "1d12f124072e"
  - COMMIT_AUTHOR_EMAIL: "wenzhixin2010@gmail.com"
